//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagerApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagerApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not assigned.
        /// </summary>
        public static string AssignmentMessage {
            get {
                return ResourceManager.GetString("AssignmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select your preferred language for the interface:.
        /// </summary>
        public static string ChooseLanguage_Description {
            get {
                return ResourceManager.GetString("ChooseLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string ChooseLanguage_English {
            get {
                return ResourceManager.GetString("ChooseLanguage_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на German.
        /// </summary>
        public static string ChooseLanguage_German {
            get {
                return ResourceManager.GetString("ChooseLanguage_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string ChooseLanguage_NextButton {
            get {
                return ResourceManager.GetString("ChooseLanguage_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can change the language later in application settings..
        /// </summary>
        public static string ChooseLanguage_Note {
            get {
                return ResourceManager.GetString("ChooseLanguage_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string ChooseLanguage_Russian {
            get {
                return ResourceManager.GetString("ChooseLanguage_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language Selection.
        /// </summary>
        public static string ChooseLanguage_Title {
            get {
                return ResourceManager.GetString("ChooseLanguage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose worker.
        /// </summary>
        public static string ChooseWorker {
            get {
                return ResourceManager.GetString("ChooseWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CANCEL.
        /// </summary>
        public static string DialogButtonPanel_CancelButton {
            get {
                return ResourceManager.GetString("DialogButtonPanel_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string DialogButtonPanel_OkButton {
            get {
                return ResourceManager.GetString("DialogButtonPanel_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field can&apos;t be empty.
        /// </summary>
        public static string EmptyField {
            get {
                return ResourceManager.GetString("EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assign to worker:.
        /// </summary>
        public static string InputDialog_AssignToWorker {
            get {
                return ResourceManager.GetString("InputDialog_AssignToWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input Dialog.
        /// </summary>
        public static string InputDialog_Title {
            get {
                return ResourceManager.GetString("InputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select your Language.
        /// </summary>
        public static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select language.
        /// </summary>
        public static string LanguageSelectionDescription {
            get {
                return ResourceManager.GetString("LanguageSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string LoginWindow_Authorization {
            get {
                return ResourceManager.GetString("LoginWindow_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginWindow_Login {
            get {
                return ResourceManager.GetString("LoginWindow_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string LoginWindow_Password {
            get {
                return ResourceManager.GetString("LoginWindow_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string LoginWindow_Register {
            get {
                return ResourceManager.GetString("LoginWindow_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task manager.
        /// </summary>
        public static string LoginWindow_TaskManager {
            get {
                return ResourceManager.GetString("LoginWindow_TaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username.
        /// </summary>
        public static string LoginWindow_Username {
            get {
                return ResourceManager.GetString("LoginWindow_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string MainWindow_ActionsColumn {
            get {
                return ResourceManager.GetString("MainWindow_ActionsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Process.
        /// </summary>
        public static string MainWindow_AddProcessButton {
            get {
                return ResourceManager.GetString("MainWindow_AddProcessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter process name:.
        /// </summary>
        public static string MainWindow_AddProcessLabel {
            get {
                return ResourceManager.GetString("MainWindow_AddProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add process.
        /// </summary>
        public static string MainWindow_AddProcessTitle {
            get {
                return ResourceManager.GetString("MainWindow_AddProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Task.
        /// </summary>
        public static string MainWindow_AddTaskButton {
            get {
                return ResourceManager.GetString("MainWindow_AddTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter task name:.
        /// </summary>
        public static string MainWindow_AddTaskLabel {
            get {
                return ResourceManager.GetString("MainWindow_AddTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add task.
        /// </summary>
        public static string MainWindow_AddTaskTitle {
            get {
                return ResourceManager.GetString("MainWindow_AddTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only administrator can add processes.
        /// </summary>
        public static string MainWindow_AdminOnlyAddProcesses {
            get {
                return ResourceManager.GetString("MainWindow_AdminOnlyAddProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only administrator can edit processes.
        /// </summary>
        public static string MainWindow_AdminOnlyEditProcesses {
            get {
                return ResourceManager.GetString("MainWindow_AdminOnlyEditProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assigned To.
        /// </summary>
        public static string MainWindow_AssignedToColumn {
            get {
                return ResourceManager.GetString("MainWindow_AssignedToColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string MainWindow_ConfirmationTitle {
            get {
                return ResourceManager.GetString("MainWindow_ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        public static string MainWindow_CreatedColumn {
            get {
                return ResourceManager.GetString("MainWindow_CreatedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data updated successfully.
        /// </summary>
        public static string MainWindow_DataUpdated {
            get {
                return ResourceManager.GetString("MainWindow_DataUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string MainWindow_DeleteButton {
            get {
                return ResourceManager.GetString("MainWindow_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete process &apos;{0}&apos; and all its tasks?.
        /// </summary>
        public static string MainWindow_DeleteProcessConfirmation {
            get {
                return ResourceManager.GetString("MainWindow_DeleteProcessConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete task &apos;{0}&apos;?.
        /// </summary>
        public static string MainWindow_DeleteTaskConfirmation {
            get {
                return ResourceManager.GetString("MainWindow_DeleteTaskConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string MainWindow_EditButton {
            get {
                return ResourceManager.GetString("MainWindow_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new process name:.
        /// </summary>
        public static string MainWindow_EditProcessLabel {
            get {
                return ResourceManager.GetString("MainWindow_EditProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit process.
        /// </summary>
        public static string MainWindow_EditProcessTitle {
            get {
                return ResourceManager.GetString("MainWindow_EditProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new task name:.
        /// </summary>
        public static string MainWindow_EditTaskLabel {
            get {
                return ResourceManager.GetString("MainWindow_EditTaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Edit process.
        /// </summary>
        public static string MainWindow_EditTaskTitle {
            get {
                return ResourceManager.GetString("MainWindow_EditTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string MainWindow_ErrorTitle {
            get {
                return ResourceManager.GetString("MainWindow_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string MainWindow_IDColumn {
            get {
                return ResourceManager.GetString("MainWindow_IDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process &apos;{0}&apos; added successfully!.
        /// </summary>
        public static string MainWindow_ProcessAddedSuccess {
            get {
                return ResourceManager.GetString("MainWindow_ProcessAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process and all its tasks deleted.
        /// </summary>
        public static string MainWindow_ProcessDeletedSuccess {
            get {
                return ResourceManager.GetString("MainWindow_ProcessDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process name cannot be empty.
        /// </summary>
        public static string MainWindow_ProcessNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("MainWindow_ProcessNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process Name.
        /// </summary>
        public static string MainWindow_ProcessNameColumn {
            get {
                return ResourceManager.GetString("MainWindow_ProcessNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process updated successfully.
        /// </summary>
        public static string MainWindow_ProcessUpdatedSuccess {
            get {
                return ResourceManager.GetString("MainWindow_ProcessUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string MainWindow_RefreshButton {
            get {
                return ResourceManager.GetString("MainWindow_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First select a process to add a task.
        /// </summary>
        public static string MainWindow_SelectProcessFirst {
            get {
                return ResourceManager.GetString("MainWindow_SelectProcessFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string MainWindow_StatusColumn {
            get {
                return ResourceManager.GetString("MainWindow_StatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string MainWindow_SuccessTitle {
            get {
                return ResourceManager.GetString("MainWindow_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task Management System.
        /// </summary>
        public static string MainWindow_SystemTitle {
            get {
                return ResourceManager.GetString("MainWindow_SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processes.
        /// </summary>
        public static string MainWindow_TabProcesses {
            get {
                return ResourceManager.GetString("MainWindow_TabProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks.
        /// </summary>
        public static string MainWindow_TabTasks {
            get {
                return ResourceManager.GetString("MainWindow_TabTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task &apos;{0}&apos; added successfully!.
        /// </summary>
        public static string MainWindow_TaskAddedSuccess {
            get {
                return ResourceManager.GetString("MainWindow_TaskAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task Count.
        /// </summary>
        public static string MainWindow_TaskCountColumn {
            get {
                return ResourceManager.GetString("MainWindow_TaskCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task deleted.
        /// </summary>
        public static string MainWindow_TaskDeletedSuccess {
            get {
                return ResourceManager.GetString("MainWindow_TaskDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task name cannot be empty.
        /// </summary>
        public static string MainWindow_TaskNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("MainWindow_TaskNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task Name.
        /// </summary>
        public static string MainWindow_TaskNameColumn {
            get {
                return ResourceManager.GetString("MainWindow_TaskNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task updated successfully.
        /// </summary>
        public static string MainWindow_TaskUpdatedSuccess {
            get {
                return ResourceManager.GetString("MainWindow_TaskUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task manager.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total Tasks:.
        /// </summary>
        public static string MainWindow_TotalTasksLabel {
            get {
                return ResourceManager.GetString("MainWindow_TotalTasksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string MainWindow_WarningTitle {
            get {
                return ResourceManager.GetString("MainWindow_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can delete only your own tasks.
        /// </summary>
        public static string MainWindow_WorkerCanDeleteOnlyOwnTasks {
            get {
                return ResourceManager.GetString("MainWindow_WorkerCanDeleteOnlyOwnTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can edit only your own tasks.
        /// </summary>
        public static string MainWindow_WorkerCanEditOnlyOwnTasks {
            get {
                return ResourceManager.GetString("MainWindow_WorkerCanEditOnlyOwnTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (your tasks).
        /// </summary>
        public static string MainWindow_YourTasksCount {
            get {
                return ResourceManager.GetString("MainWindow_YourTasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string RegisterWindow_EmailLabel {
            get {
                return ResourceManager.GetString("RegisterWindow_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New User Registration.
        /// </summary>
        public static string RegisterWindow_Header {
            get {
                return ResourceManager.GetString("RegisterWindow_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string RegisterWindow_PasswordLabel {
            get {
                return ResourceManager.GetString("RegisterWindow_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string RegisterWindow_RegisterButton {
            get {
                return ResourceManager.GetString("RegisterWindow_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        public static string RegisterWindow_Title {
            get {
                return ResourceManager.GetString("RegisterWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Username:.
        /// </summary>
        public static string RegisterWindow_UsernameLabel {
            get {
                return ResourceManager.GetString("RegisterWindow_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uncorrect name or password .
        /// </summary>
        public static string UncorrectNamePasswordMessage {
            get {
                return ResourceManager.GetString("UncorrectNamePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
